- title: "Engraved Drinkware"
  category: "Custom Engravings"
  description: "Custom mugs, tumblers & bottles with your text or logo. Perfect for gifts."
  features:
    - "Custom Text"
    - "Logo Upload"
    - "Multiple Materials"
  price: "Starting at $15"
  turnaround: "3-7 days"
  image: "/assets/img/bgblue01.jpg"
  alt: "Engraved Drinkware"
  cta_link: "/contact/?product=drinkware"
  cta_text: "Request Quote"

- title: "Nameplates & Badges"
  category: "Professional ID"
  description: "Professional nameplates and badges for offices. Various materials & finishes available."
  features:
    - "Multiple Sizes"
    - "Premium Finishes"
    - "Magnetic Back"
  price: "Starting at $12"
  turnaround: "3-5 days"
  image: "/assets/img/theflag.png"
  alt: "Nameplates & Badges"
  cta_link: "/contact/?product=nameplates"
  cta_text: "Request Quote"

- title: "Plaques & Awards"
  category: "Recognition"
  description: "Custom plaques & awards for recognition ceremonies. Premium materials & craftsmanship."
  features:
    - "Wood & Metal"
    - "Custom Shapes"
    - "Gift Ready"
  price: "Starting at $25"
  turnaround: "5-7 days"
  image: "/assets/img/dilogo.png"
  alt: "Plaques & Awards"
  cta_link: "/contact/?product=plaques"
  cta_text: "Request Quote"

- title: "Ceramic 3D Prints"
  category: "Art & Prototypes"
  description: "Custom ceramic art & prototypes using 3D printing technology. Perfect for unique decor."
  features:
    - "Custom Designs"
    - "Food Safe"
    - "Glazed Finish"
  price: "Starting at $30"
  turnaround: "7-10 days"
  image: "/assets/img/bgblue01.jpg"
  alt: "Ceramic 3D Prints"
  cta_link: "/contact/?product=ceramic"
  cta_text: "Request Quote"

- title: "Limited Drops"
  category: "Exclusive Items"
  description: "Exclusive limited-quantity items with unique designs. Perfect for collectors & special occasions."
  features:
    - "Limited Quantity"
    - "Premium Materials"
    - "Collectible"
  price: "Varies"
  turnaround: "Available Now"
  image: "/assets/img/theflag.png"
  alt: "Limited Edition Items"
  cta_link: "/contact/?product=limited"
  cta_text: "Check Availability"

- title: "Custom Projects"
  category: "Bespoke Design"
  description: "Have something specific in mind? We create custom pieces tailored to your specifications."
  features:
    - "Your Design"
    - "Any Material"
    - "Full Service"
  price: "Quote Based"
  turnaround: "Varies"
  image: "/assets/img/dilogo.png"
  alt: "Custom Orders"
  cta_link: "/contact/?custom=true"
  cta_text: "Start Project"
