- tagline: "Create. Launch. Grow."
  badges: ["Veteran‑Owned", "Dallas, TX", "Fast, secure hosting", "Real support"]
  colors:
    burgundy: "#7B1E3F"
    gold: "#D4AF37"
    black: "#111111"
    wheat: "#F2E8D5"
- tagline: "New tagline"
